apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rolling
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: rolling
    spec:
      containers:
      - name: rolling
        image: sthuthi11/rolling:v1
        ports:
        - containerPort: 80
