apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: website
    color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
      color: blue
  template:
    metadata:
      labels:
        app: website
        color: blue
    spec:
      containers:
        - name: orgpulse-blue
          image: orgpulse:blue
          ports:
            - containerPort: 80
